version: '3.1'

services:
  main-service:
    image: 'aligator9/my-pet-bitlab-med-project'
    container_name: 'my-pet-bitlab-med-project'
    depends_on:
      - bitlab-med-database
    ports:
      - 7777:8080
    environment:
      - SERVER_PORT=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://bitlab-med-database:5432/bitlabMed
      - SPRING_DATASOURCE_USERNAME=bitlab-med
      - SPRING_DATASOURCE_PASSWORD=almas0606
      - SPRING_APPLICATION_NAME=bitlabMed
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db.changelog/db.changelog-master.xml
      - SERVER_SERVLET_SESSION_TIMEOUT=30m
      - SERVER_SERVLET_SESSION_COOKIE_NAME=MY_SESSION_COOKIE
      - SPRING_WEB_LOCALE=ru
      - SPRING_WEB_LOCALE_RESOLVER=fixed

      
  bitlab-med-database:
    image: 'postgres'
    container_name: 'bitlab-med-database-container'
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=bitlab-med
      - POSTGRES_PASSWORD=almas0606
      - POSTGRES_DB=bitlabMed
